version: "3.8"

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: soft-pinko-back-end:task5
    ports:
      - "5252"

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: soft-pinko-front-end:task5
    ports:
      - "9000"
    depends_on:
      - back-end
  
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: soft-pinko-proxy:task5
    ports:
      - "80:80"

networks:
  default:
    driver: bridge
